"""
trader-scorer-trade skill — Python handler (stub).

Currently unused at runtime: per-trade reviews are generated by the
TS side at apps/market_dashboard/src/lib/generate-trade-verdict.ts.
Stub kept so the canonical 7-file layout is honoured.
"""
SKILL_NAME = "trader-scorer-trade"
