"""
moomoo OpenD live-quote daemon.

Streams real-time quotes for indices, sector ETFs, and the current TV screener
hits from a locally running moomoo OpenD daemon, throttles to one POST per
symbol per ~15 s, and pushes batches to the Vercel-hosted ingest endpoint.

Tickers are loaded from data/tv_screeners.json (generated by tv_screener_fetch.py)
so the live-quote universe always matches what's on the dashboard screener tab.
Falls back to a small hardcoded list if the file is absent.

Run while you're trading, e.g.
  python scripts/live_quote_daemon.py

Or schedule via Windows Task Scheduler at 13:25 UTC daily, stopping at 21:00.

Required env (read from repo-root .env or environment):
  LIVE_QUOTE_INGEST_KEY — shared secret matching the Vercel /api/live-quotes/ingest route
  VERCEL_INGEST_URL     — base URL, e.g. https://market-dashboard.vercel.app
  MOOMOO_OPEND_HOST     — defaults to 127.0.0.1
  MOOMOO_OPEND_PORT     — defaults to 11111

Falls back to a noisy stub mode (random walk) when futu SDK or OpenD is
unavailable, so the path can be tested end-to-end without OpenD running.
Stub mode is enabled by passing --stub.
"""
from __future__ import print_function
import argparse
import datetime
import json
import os
import random
import sys
import time
import urllib.error
import urllib.request

# --------------------------------------------------------------------------
# .env loader (mirrors the pattern used by build_data.py / morning_brief.py)
# --------------------------------------------------------------------------

def _load_env():
    here = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.normpath(os.path.join(here, "..", "..", ".."))
    env_path = os.path.join(repo_root, ".env")
    if not os.path.exists(env_path):
        return
    with open(env_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key and key not in os.environ:
                os.environ[key] = value

_load_env()

# --------------------------------------------------------------------------
# Symbol universe
# --------------------------------------------------------------------------

INDEX_SYMBOLS = ["SPY", "QQQ", "IWM", "DIA"]   # ^VIX handled separately (different futu code)
SECTOR_SYMBOLS = ["XLK", "XLF", "XLE", "XLV", "XLI", "XLY", "XLP", "XLU", "XLB", "XLRE", "XLC"]

# Fallback if tv_screeners.json is absent
_FALLBACK_WATCHLIST = ["NVDA", "TSLA", "AAPL", "MSFT", "AMZN", "META",
                        "GOOGL", "AMD", "SMCI", "PLTR", "CRWD", "MSTR"]


def _load_screener_tickers() -> list:
    """Return unique tickers from data/tv_screeners.json, or fallback list."""
    here = os.path.dirname(os.path.abspath(__file__))
    data_path = os.path.join(here, "..", "data", "tv_screeners.json")
    data_path = os.path.normpath(data_path)
    if not os.path.exists(data_path):
        print("[symbols] tv_screeners.json not found — using fallback watchlist", flush=True)
        return list(_FALLBACK_WATCHLIST)
    with open(data_path, encoding="utf-8") as f:
        data = json.load(f)
    tickers = []
    seen = set()
    for screener in data.get("screeners", []):
        for hit in screener.get("hits", []):
            sym = hit.get("ticker", "").strip().upper()
            # skip preferred shares, warrants, rights (contain / . - or digits+letters hybrid)
            if not sym or not sym.isalpha():
                continue
            if sym not in seen:
                seen.add(sym)
                tickers.append(sym)
    if not tickers:
        print("[symbols] tv_screeners.json had no hits — using fallback watchlist", flush=True)
        return list(_FALLBACK_WATCHLIST)
    print("[symbols] loaded %d screener tickers from tv_screeners.json" % len(tickers), flush=True)
    return tickers


SCREENER_SYMBOLS = _load_screener_tickers()

# moomoo OpenD free-tier quota = 100 symbols total (subscription).
# Reserve headroom of 5 for any in-flight subscriptions / late additions.
# Universe priority: indices > sector ETFs > top-N screener picks.
MOOMOO_SUBSCRIPTION_QUOTA = 100
SUBSCRIPTION_HEADROOM = 5
MAX_SUBSCRIBED = MOOMOO_SUBSCRIPTION_QUOTA - SUBSCRIPTION_HEADROOM  # = 95

# Dedupe across categories (screener may include SPY/QQQ/sector ETFs).
_seen = set()
def _dedupe(lst):
    out = []
    for s in lst:
        if s not in _seen:
            _seen.add(s)
            out.append(s)
    return out

_INDEX = _dedupe(INDEX_SYMBOLS)
_SECTORS = _dedupe(SECTOR_SYMBOLS)
_SCREENER_REMAINING = _dedupe(SCREENER_SYMBOLS)
# Reserve slots for indices + sectors first; fill remaining with top screener picks
_top_screener_slots = max(0, MAX_SUBSCRIBED - len(_INDEX) - len(_SECTORS))
ALL_SYMBOLS = _INDEX + _SECTORS + _SCREENER_REMAINING[:_top_screener_slots]

if len(_SCREENER_REMAINING) > _top_screener_slots:
    dropped = len(_SCREENER_REMAINING) - _top_screener_slots
    print("[symbols] capping universe at %d (moomoo quota %d, headroom %d). "
          "Dropped %d screener tickers." %
          (len(ALL_SYMBOLS), MOOMOO_SUBSCRIPTION_QUOTA, SUBSCRIPTION_HEADROOM, dropped),
          flush=True)
else:
    print("[symbols] universe = %d (indices=%d, sectors=%d, screener=%d)" %
          (len(ALL_SYMBOLS), len(_INDEX), len(_SECTORS), len(_SCREENER_REMAINING)),
          flush=True)


def to_futu_code(sym):
    """Convert plain symbol to futu's US.SPY format."""
    return "US." + sym


# --------------------------------------------------------------------------
# HTTP push
# --------------------------------------------------------------------------

CHUNK_SIZE = 15      # symbols per HTTP POST (route upserts one-by-one)
HTTP_TIMEOUT = 30    # seconds per chunk


def _post_chunk(url, key, chunk):
    body = json.dumps({"quotes": chunk, "mode": "primary"}).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=body,
        method="POST",
        headers={
            "Content-Type": "application/json",
            "Authorization": "Bearer " + key,
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=HTTP_TIMEOUT) as r:
            payload = json.loads(r.read().decode("utf-8"))
            return payload.get("written", 0), payload.get("skipped", 0), None
    except urllib.error.HTTPError as e:
        return 0, len(chunk), "HTTP %s: %s" % (e.code, e.read().decode("utf-8", "ignore")[:200])
    except Exception as e:
        return 0, len(chunk), str(e)


def push_batch(quotes):
    base = os.environ.get("VERCEL_INGEST_URL")
    key = os.environ.get("LIVE_QUOTE_INGEST_KEY")
    if not base or not key:
        print("[push_batch] missing VERCEL_INGEST_URL or LIVE_QUOTE_INGEST_KEY - skipping", flush=True)
        return False
    url = base.rstrip("/") + "/api/live-quotes/ingest"

    total_written = 0
    total_skipped = 0
    errors = []
    chunks = [quotes[i:i + CHUNK_SIZE] for i in range(0, len(quotes), CHUNK_SIZE)]
    for i, chunk in enumerate(chunks, 1):
        w, s, err = _post_chunk(url, key, chunk)
        total_written += w
        total_skipped += s
        if err:
            errors.append("chunk %d/%d: %s" % (i, len(chunks), err))
    if errors:
        for e in errors:
            print("[push_batch] " + e, flush=True)
    print("[push_batch] %d chunks | wrote=%d skipped=%d" % (
        len(chunks), total_written, total_skipped
    ), flush=True)
    return total_written > 0


# --------------------------------------------------------------------------
# moomoo OpenD client (futu-api)
# --------------------------------------------------------------------------

def run_moomoo(throttle_s):
    try:
        from futu import OpenQuoteContext, RET_OK, SubType
    except ImportError:
        print("[moomoo] futu-api not installed — pip install futu-api", file=sys.stderr)
        return False

    host = os.environ.get("MOOMOO_OPEND_HOST", "127.0.0.1")
    port = int(os.environ.get("MOOMOO_OPEND_PORT", "11111"))

    ctx = OpenQuoteContext(host=host, port=port)
    futu_codes = [to_futu_code(s) for s in ALL_SYMBOLS]

    # Chunk subscribe — moomoo per-call subscribe limit is 50 symbols.
    # We send in batches of 40 with a 0.5s delay so the OpenD client has time
    # to ACK each chunk before the next request goes out.
    SUBSCRIBE_BATCH = 40
    SUBSCRIBE_DELAY_S = 0.5
    subscribed_count = 0
    failed_chunks = []
    for i in range(0, len(futu_codes), SUBSCRIBE_BATCH):
        chunk = futu_codes[i:i + SUBSCRIBE_BATCH]
        ret_sub, err_sub = ctx.subscribe(chunk, [SubType.QUOTE])
        if ret_sub != RET_OK:
            failed_chunks.append("batch %d-%d: %s" % (i, i + len(chunk), err_sub))
        else:
            subscribed_count += len(chunk)
        time.sleep(SUBSCRIBE_DELAY_S)

    if subscribed_count == 0:
        print("[moomoo] subscribe failed entirely: %s" % "; ".join(failed_chunks), file=sys.stderr)
        ctx.close()
        return False

    if failed_chunks:
        for fc in failed_chunks:
            print("[moomoo] partial subscribe failure: %s" % fc, file=sys.stderr)

    print("[moomoo] connected to OpenD at %s:%d, subscribed %d/%d symbols" %
          (host, port, subscribed_count, len(futu_codes)), flush=True)

    last_push = {}  # symbol -> ts

    try:
        while True:
            ret, df = ctx.get_stock_quote(futu_codes)
            if ret != RET_OK:
                print("[moomoo] get_stock_quote failed: %s" % df, flush=True)
                time.sleep(5)
                continue

            now_ts = time.time()
            now_iso = datetime.datetime.now(datetime.timezone.utc).isoformat()
            batch = []
            for _, row in df.iterrows():
                code = row["code"]                         # "US.SPY"
                sym = code.split(".", 1)[1] if "." in code else code
                price = float(row["last_price"])
                prev_close = float(row.get("prev_close_price") or 0) or None
                change_pct = None
                if prev_close:
                    change_pct = (price - prev_close) / prev_close * 100.0
                volume = int(row.get("volume") or 0) or None

                last = last_push.get(sym, 0)
                if now_ts - last < throttle_s:
                    continue

                batch.append({
                    "symbol": sym,
                    "price": price,
                    "changePct": change_pct,
                    "volume": volume,
                    "source": "moomoo",
                    "observedAt": now_iso,
                })
                last_push[sym] = now_ts

            if batch:
                push_batch(batch)

            time.sleep(2)  # polling cadence; throttle_s gates push frequency per symbol
    except KeyboardInterrupt:
        print("[moomoo] interrupted", flush=True)
    finally:
        ctx.close()
    return True


# --------------------------------------------------------------------------
# Stub mode (random walk) — for local testing without OpenD
# --------------------------------------------------------------------------

def run_stub(throttle_s):
    print("[stub] random-walk mode for testing", flush=True)
    state = {s: 100.0 + random.uniform(-10, 10) for s in ALL_SYMBOLS}
    while True:
        now_iso = datetime.datetime.now(datetime.timezone.utc).isoformat()
        batch = []
        for sym in ALL_SYMBOLS:
            state[sym] *= 1 + random.uniform(-0.001, 0.001)
            batch.append({
                "symbol": sym,
                "price": round(state[sym], 4),
                "changePct": round(random.uniform(-2, 2), 3),
                "volume": random.randint(100_000, 5_000_000),
                "source": "moomoo",  # advertise as moomoo so the server treats it as primary
                "observedAt": now_iso,
            })
        push_batch(batch)
        time.sleep(throttle_s)


# --------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--throttle", type=float, default=15.0,
                        help="min seconds between pushes per symbol")
    parser.add_argument("--stub", action="store_true",
                        help="random-walk mode for testing without OpenD")
    args = parser.parse_args()

    if args.stub:
        run_stub(args.throttle)
        return

    ok = run_moomoo(args.throttle)
    if not ok:
        sys.exit(1)


if __name__ == "__main__":
    main()
