/**
 * morning-brief skill — TS handler (server-only).
 *
 * Currently unused at runtime: the morning brief is generated by
 * the Python CLI (apps/market_dashboard_backend/scripts/morning_brief.py)
 * during the daily CI cron. Kept as a stub so the canonical 7-file
 * layout is honoured and a future Next.js route can call it directly.
 */
import fs from "node:fs";
import path from "node:path";

const ROOT = path.dirname(new URL(import.meta.url).pathname);
const PROMPT = fs.readFileSync(path.join(ROOT, "prompt.md"), "utf8");

export const DEFAULT_WATCHLIST = [
  "NVDA", "TSLA", "AAPL", "MSFT", "AMZN", "META",
  "GOOGL", "AMD", "SMCI", "PLTR", "CRWD", "MSTR",
];

export function buildPrompt(
  dateStr: string,
  watchlist: string[] = DEFAULT_WATCHLIST
): string {
  const watchlistStr = watchlist.join(", ");
  return PROMPT.split("{date_str}").join(dateStr).split("{watchlist_str}").join(watchlistStr);
}
