/**
 * trader-scorer-market skill — TS handler (stub).
 *
 * Currently unused at runtime: the daily market verdict is generated by
 * apps/market_dashboard_backend/scripts/trader_verdict.py during the
 * CI cron. Kept as a stub so the canonical 7-file layout is honoured.
 */
export const SKILL_NAME = "trader-scorer-market" as const;
