"""
trader-scorer-stock skill — Python handler (stub).

Currently unused at runtime: per-stock analysis is generated by the
TS API route at apps/market_dashboard/src/app/api/analysis/stock/route.ts.
Stub kept so the canonical 7-file layout is honoured.
"""
SKILL_NAME = "trader-scorer-stock"
