"use client";

import { useEffect, useState } from "react";
import type { MarketSnapshot } from "@/types/market-dashboard";

const BASE = "/market-dashboard";

/**
 * Fetches the daily market snapshot from `public/market-dashboard/snapshot.json`.
 * Mirrors the `useBreadth()` pattern — one load per page mount, no polling
 * (the snapshot is regenerated by refresh_data.yml, not at request time).
 */
export function useMarketSnapshot() {
  const [data, setData] = useState<MarketSnapshot | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;
    fetch(`${BASE}/snapshot.json`, { cache: "no-store" })
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json() as Promise<MarketSnapshot>;
      })
      .then((j) => {
        if (!cancelled) {
          setData(j);
          setLoading(false);
        }
      })
      .catch((e) => {
        if (!cancelled) {
          setError((e as Error).message);
          setLoading(false);
        }
      });
    return () => {
      cancelled = true;
    };
  }, []);

  return { data, error, loading };
}
