# install.ps1 -- dashboard-bridge Windows installer
#
# What it does:
#   1. Creates a Python virtualenv in .venv\
#   2. Installs moomoo-api + requests + tomli into the venv
#   3. Prompts for your dashboard URL, bridge token, broker alias, moomoo acc_id
#   4. Writes ~/.config/dashboard-bridge.toml
#   5. Registers a Windows scheduled task that:
#        - Runs the bridge on user login
#        - Re-launches it every 5 minutes if it dies
#        - Uses the venv's python
#
# Usage:
#   .\install.ps1                          # interactive
#   .\install.ps1 -Reconfigure             # re-prompt config, leave task alone
#   .\install.ps1 -SkipTask                # config + venv only, no scheduled task
#   .\install.ps1 -UseExistingConfig       # only (re)install venv + task

[CmdletBinding()]
param(
    [switch]$Reconfigure,
    [switch]$SkipTask,
    [switch]$UseExistingConfig
)

$ErrorActionPreference = "Stop"

# --- Paths ------------------------------------------------------------------

$BridgeDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$VenvDir = Join-Path $BridgeDir ".venv"
$VenvPython = Join-Path $VenvDir "Scripts\python.exe"
$ConfigDir = Join-Path $env:USERPROFILE ".config"
$ConfigPath = Join-Path $ConfigDir "dashboard-bridge.toml"
$ExampleConfig = Join-Path $BridgeDir "dashboard-bridge.example.toml"
$TaskName = "DashboardBridge"

# --- Helpers ----------------------------------------------------------------

function Get-PythonExe {
    $candidates = @("python", "python3", "py")
    foreach ($c in $candidates) {
        try {
            $v = & $c --version 2>$null
            if ($LASTEXITCODE -eq 0) { return $c }
        } catch {}
    }
    throw "Python 3.10+ not found in PATH. Install from https://www.python.org/downloads/"
}

function Prompt-NonEmpty {
    param([string]$Prompt, [string]$Default = "")
    while ($true) {
        $msg = if ($Default) { "$Prompt [$Default]" } else { $Prompt }
        $val = Read-Host $msg
        if (-not $val -and $Default) { return $Default }
        if ($val) { return $val }
    }
}

# --- 1. Create venv + install deps ------------------------------------------

if (-not (Test-Path $VenvDir)) {
    Write-Host "Creating virtualenv at $VenvDir ..."
    $py = Get-PythonExe
    & $py -m venv $VenvDir
}

Write-Host "Installing/upgrading bridge dependencies ..."
& $VenvPython -m pip install --upgrade pip --quiet
& $VenvPython -m pip install -r (Join-Path $BridgeDir "requirements.txt") --quiet

# --- 2. Write config (interactive unless -UseExistingConfig) ----------------

if (-not $UseExistingConfig) {
    if ((Test-Path $ConfigPath) -and (-not $Reconfigure)) {
        Write-Host "Config already exists at $ConfigPath -- keeping it (use -Reconfigure to rewrite)."
    } else {
        Write-Host ""
        Write-Host "--- Bridge configuration ---"
        $dashUrl = Prompt-NonEmpty "Dashboard URL" "https://market-dashboard-ivory.vercel.app"
        Write-Host ""
        Write-Host "Open $dashUrl/dashboard/settings/brokers and click 'Generate token'."
        Write-Host "Paste the token below (you'll only see it once on the dashboard):"
        $token = Prompt-NonEmpty "Bridge token"
        $alias = Prompt-NonEmpty "Broker account alias (must match dashboard)" "moomoo Malaysia"
        $accId = Prompt-NonEmpty "moomoo real account id" "286260077786655984"
        $firm = Prompt-NonEmpty "Security firm" "FUTUMY"
        $market = Prompt-NonEmpty "Market" "US"

        if (-not (Test-Path $ConfigDir)) {
            New-Item -ItemType Directory -Path $ConfigDir | Out-Null
        }

        $configContent = @"
# Generated by install.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
[dashboard]
url = "$dashUrl"
token = "$token"
# Optional secrets for live prices + local post-close breadth refresh:
# live_quote_key = "LIVE_QUOTE_INGEST_KEY"
# brief_ingest_key = "BRIEF_INGEST_KEY"

[broker]
account_alias = "$alias"
type = "MOOMOO_$firm"

[opend]
host = "127.0.0.1"
port = 11111
acc_id = $accId
security_firm = "$firm"
market = "$market"

[sync]
interval_sec = 60
fill_lookback_days = 1
live_quote_extras = "SPY,QQQ,IWM,DIA,VIX,SMH,XLK,NVDA,CRDO,ARM,MRVL"
breadth_post_close = true
breadth_post_close_time = "16:33"
breadth_timezone = "America/New_York"
"@
        Set-Content -Path $ConfigPath -Value $configContent -Encoding utf8
        Write-Host "Wrote $ConfigPath" -ForegroundColor Green
    }
}

# --- 3. Register scheduled task ---------------------------------------------

if (-not $SkipTask) {
    Write-Host ""
    Write-Host "--- Registering scheduled task '$TaskName' ---"
    if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
        Write-Host "Existing task found -- unregistering it first ..."
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
    }

    $action = New-ScheduledTaskAction `
        -Execute $VenvPython `
        -Argument "-m bridge run" `
        -WorkingDirectory $BridgeDir

    # Two triggers: at user login + every 5 min as a watchdog re-launch
    $triggerLogin = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
    $triggerRecurring = New-ScheduledTaskTrigger -Once -At (Get-Date) `
        -RepetitionInterval (New-TimeSpan -Minutes 5) `
        -RepetitionDuration (New-TimeSpan -Days 365)

    $settings = New-ScheduledTaskSettingsSet `
        -AllowStartIfOnBatteries `
        -DontStopIfGoingOnBatteries `
        -ExecutionTimeLimit (New-TimeSpan -Hours 0) `
        -MultipleInstances IgnoreNew `
        -RestartCount 5 -RestartInterval (New-TimeSpan -Minutes 1) `
        -Hidden

    # Run as the current user (interactive -- no admin needed)
    $principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive

    Register-ScheduledTask `
        -TaskName $TaskName `
        -Description "Syncs moomoo OpenD positions and fills to Market Dashboard" `
        -Action $action `
        -Trigger @($triggerLogin, $triggerRecurring) `
        -Settings $settings `
        -Principal $principal | Out-Null

    Write-Host "Scheduled task registered." -ForegroundColor Green
    Write-Host ""
    Write-Host "Starting the bridge now ..."
    Start-ScheduledTask -TaskName $TaskName
}

Write-Host ""
Write-Host "--- Install complete ---"
Write-Host "  Config:        $ConfigPath"
Write-Host "  Logs:          $env:USERPROFILE\.dashboard-bridge.log"
Write-Host "  Scheduled task: $TaskName"
Write-Host ""
Write-Host "Quick test:"
Write-Host "  $VenvPython -m bridge dry-run"
Write-Host ""
Write-Host "Once:"
Write-Host "  $VenvPython -m bridge once"
Write-Host ""
Write-Host "Uninstall:"
Write-Host "  .\uninstall.ps1"
